"""SAA POES mapping package."""
from .load_poes import (
    NCEI_L1B_BASE,
    SAT_FILE_TOKEN,
    DEFAULT_CHANNEL,
    CHANNEL_INFO,
    build_poes_l1b_url,
    download_poes_file,
    open_poes_netcdf,
    describe_dataset,
    extract_minimal_dataframe,
    load_minimal_day,
    load_date_range,
    file_sha256,
    satellite_from_filename,
    extract_channels_dataframe,
    channel_metadata,
)
from .aggregate import (
    RangeLoad,
    load_range,
    build_grid_table,
    add_coverage_mask,
    GRID_COLUMNS,
    load_range_channels,
)
from .threshold_analysis import (
    run_sensitivity,
    save_sensitivity,
    cell_area_km2,
    haversine_km,
    flux_weighted_centroid,
    plot_threshold_overlay,
    plot_centroid_shift,
    PERCENTILES,
    SENSITIVITY_COLUMNS,
    run_channel_sensitivity,
    CHANNEL_SENSITIVITY_COLUMNS,
)
from .time_window_analysis import (
    TIME_WINDOWS,
    TIME_WINDOW_SENSITIVITY_COLUMNS,
    CUMULATIVE_LABELS,
    WEEK_LABELS,
    window_day_count,
    choose_coverage_threshold,
    region_cell_count,
    load_month_region,
    slice_window,
    add_obs_date,
    build_window_grids,
    sample_count_distribution,
    coverage_warning,
    run_time_window_sensitivity,
    plot_window_mean_map,
    plot_mean_map_panels,
    plot_sample_count_panels,
    plot_centroid_by_window,
    plot_area_by_window,
    plot_weekly_centroids,
)
from .satellite_analysis import (
    CANDIDATE_SATELLITES,
    REFERENCE_SATELLITE,
    AUDIT_COLUMNS,
    SATELLITE_SENSITIVITY_COLUMNS,
    list_archive_month_days,
    audit_satellite,
    build_satellite_audit,
    choose_pilot,
    run_satellite_sensitivity,
    plot_satellite_mean_map,
    plot_satellite_sample_count,
    plot_satellite_comparison,
    plot_satellite_centroid_comparison,
    plot_satellite_area_by_threshold,
    MULTISAT_SENSITIVITY_COLUMNS,
    PAIRWISE_DISTANCE_COLUMNS,
    satellite_family,
    run_multisatellite_sensitivity,
    pairwise_centroid_distances,
    plot_multisatellite_centroids,
    plot_pairwise_distance_heatmap,
)
from .magnetic_audit import (
    AUDIT_COLUMNS as MAG_AUDIT_COLUMNS,
    SELECTION_COLUMNS as MAG_SELECTION_COLUMNS,
    DISTRIBUTION_COLUMNS as MAG_DISTRIBUTION_COLUMNS,
    PILOT_MAGNETIC_VARS,
    audit_magnetic_variables,
    build_selection_table,
    extract_flux_plus_magnetic,
    load_region_with_magnetic,
    assign_cells,
    selected_cells_from_grid,
    footprint_magnetic_distributions,
    plot_flux_vs_variable,
    plot_high_flux_in_magnetic_space,
    plot_geographic_variable_map,
    plot_particle_footprint_reference,
)
from .magnetic_framing import (
    VALIDITY_COLUMNS,
    PROFILE_COLUMNS,
    FOOTPRINT_SUMMARY_COLUMNS,
    CONCENTRATION_COLUMNS,
    PROFILE_VARIABLES,
    SUMMARY_VARIABLES,
    valid_mask,
    magnetic_validity_table,
    add_footprint_flags,
    binned_flux_profile,
    all_binned_profiles,
    footprint_magnetic_summary,
    concentration_metrics,
    plot_flux_profile,
    plot_inside_outside,
    plot_btot_vs_l,
    plot_high_flux_btot_vs_l,
    plot_mag_lat_lon_wrapaware,
)

__all__ = [
    "NCEI_L1B_BASE",
    "SAT_FILE_TOKEN",
    "DEFAULT_CHANNEL",
    "CHANNEL_INFO",
    "build_poes_l1b_url",
    "download_poes_file",
    "open_poes_netcdf",
    "describe_dataset",
    "extract_minimal_dataframe",
    "load_minimal_day",
    "load_date_range",
    "file_sha256",
    "satellite_from_filename",
]
